export const ACTIONS = {
    GET_PRODUCTS : "GET_PRODUCTS",
    GET_PRODUCTS_SUCCESS : "GET_PRODUCTS_SUCCESS",
    GET_PRODUCTS_FAILED : "GET_PRODUCTS_FAILED",
    UPDATE_PRODUCTS : "UPDATE_PRODUCTS",
    UPDATE_PRODUCTS_SUCCESS : "UPDATE_PRODUCTS_SUCCESS",
    UPDATE_PRODUCTS_FAILED : "UPDATE_PRODUCTS_FAILED"
}