export const ACTIONS = {
    GET_SALES : "GET_SALES",
    GET_SALES_SUCCESS : "GET_SALES_SUCCESS",
    GET_SALES_FAILED : "GET_SALES_FAILED",
    CREATE_SALES : "CREATE_SALES",
    CREATE_SALES_SUCCESS : "CREATE_SALES_SUCCESS",
    CREATE_SALES_FAILED : "CREATE_SALES_FAILED",
}