export const ACTIONS = {
    GET_SALES_PERSONS : "GET_SALES_PERSONS",
    GET_SALES_PERSONS_SUCCESS : "GET_SALES_PERSONS_SUCCESS",
    GET_SALES_PERSONS_FAILED : "GET_SALES_PERSONS_FAILED",
    UPDATE_SALES_PERSONS : "UPDATE_SALES_PERSONS",
    UPDATE_SALES_PERSONS_SUCCESS : "UPDATE_SALES_PERSONS_SUCCESS",
    UPDATE_SALES_PERSONS_FAILED : "UPDATE_SALES_PERSONS_FAILED"
}